Drop full aws sdk
articulate/sqns pull request #3
Opened 2023-03-28 15:58 UTC by asolenzal

2023-03-31 13:29 UTC, lucasadrianof requested changes
Dang, this is a really nice work, I love it 🥳 .

I really liked how we were able to move away from `ramda` and use the new AWS SDK with TS with no other extra dependencies. Nice addition with the eslint plugin too 👏🏽 .

I have a few suggestions, but overall this looks great!

2023-03-31 13:29 UTC, lucasadrianof commented on src/index.ts
> +  if (topicOptions.arn !== undefined && topicOptions.arn !== null && topicOptions.arn !== '') {
```suggestion
  if (topicOptions?.arn) {
```

2023-03-31 13:29 UTC, lucasadrianof commented on test/_setup.ts
Do we still need `nock` here? I think we could remove this file and that dependency, the `aws-sdk-client-mock` we're using already prevents the SDK from hitting the real AWS URL.

2023-03-31 13:29 UTC, lucasadrianof commented on tsconfig.json
> +}
```suggestion
}

```

2023-03-31 13:29 UTC, lucasadrianof commented on src/index.ts
> +    if (topicOptions.filterPolicy !== null) {
```suggestion
    if (topicOptions.filterPolicy) {
```

2023-03-31 13:29 UTC, lucasadrianof commented on src/index.ts
> +      .then((attributes: GetQueueAttributesCommandOutput) => attributes.Attributes?.QueueArn)
Could we add one more test case covering the scenario when this attribute is not returned? I ran a quick coverage on this branch with your changes and this is the only bit not covered. If we add a test validating this we'll get 100% coverage 🥳 .

![image](https://user-images.githubusercontent.com/13476437/229131878-34f162c5-c77e-43f4-964d-1a9afacd453b.png)


```suggestion
      .then((attributes) => attributes.Attributes?.QueueArn)
```

2023-03-31 13:29 UTC, lucasadrianof commented on src/types.ts
Could we alpha-sort the interfaces on this file? 🙇🏽‍♂️

2023-03-31 13:29 UTC, lucasadrianof commented on package.json
> +    "eslint-plugin-promise": "^6.0.0",
Are we using these plugins? I don't see any references to them in the eslint config file.

2023-04-03 13:38 UTC, asolenzal commented
@lucasadrianof All comments addressed, feel free to check again.

2023-04-05 18:56 UTC, merged